### ISSUE TITLE
chainsail-helpers on PyPi is an old version

### ISSUE THREAD

**Issue by Etjean** [tweag/chainsail-resources#8]
The version of `chainsail-helpers` on PyPi is the version that precedes the bugfix introduced in #2 (apologies for missing that in my review btw). @simeoncarstens, I can't update it myself since it is protected with your PyPi credentials.

**Comment by simeoncarstens** [comment]
Thanks! I just merged #7 and updated the version on PyPi accordingly. It's now 0.1.2.
